#!/usr/bin/env node
/* hardest/difficulty.mjs — write DIFFICULTY.md: autopilot deaths/time per level.
 * Difficulty proxy for re-balance passes; deterministic, no browser needed. */
import { createRequire } from 'node:module';
import { readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const DIR = dirname(fileURLToPath(import.meta.url));
require(join(DIR, 'engine.js'));
require(join(DIR, 'autopilot.js'));
const A = globalThis.HardestAutopilot;

const TIERS = [[10, 'WARM-UP'], [20, 'DEMANDING'], [30, 'BRUTAL'], [40, 'HARD+'], [50, 'SAVAGE'], [60, 'NIGHTMARE'], [120, 'INHUMAN'], [Infinity, 'APEX']];
const tierOf = id => TIERS.find(([m]) => id <= m)[1];
const files = readdirSync(join(DIR, 'levels')).filter(f => f.endsWith('.js')).sort();
const rows = [];
for (const f of files) {
  globalThis.HARDEST_LEVELS = [];
  require(join(DIR, 'levels', f));
  const lvl = globalThis.HARDEST_LEVELS[0];
  if (!lvl || !Number.isInteger(lvl.id)) continue;
  const r = A.solve(lvl, { maxSim: 120, maxDeaths: 400 });
  rows.push({ id: lvl.id, name: lvl.name, file: f, clear: r.clear, time: r.time, deaths: r.deaths, reason: r.reason });
}
let md = `# Difficulty report — generated by difficulty.mjs (${new Date().toISOString().slice(0, 10)})

Autopilot clear stats per level (deterministic, seed 1). Deaths/time are a
difficulty PROXY — a greedy bot, not a human. Use for re-balance passes.

| id | level | tier | clear | auto deaths | auto time (s) |
|---:|---|---|---|---:|---:|
`;
for (const r of rows.sort((a, b) => a.id - b.id)) {
  md += `| ${r.id} | ${r.name} | ${tierOf(r.id)} | ${r.clear ? 'yes' : 'NO (' + r.reason + ')'} | ${r.deaths} | ${r.time.toFixed(1)} |\n`;
}
writeFileSync(join(DIR, 'DIFFICULTY.md'), md);
console.log(`DIFFICULTY.md: ${rows.length} levels`);
