#!/usr/bin/env node
/* hardest/gen-pars.mjs — regenerate pars.js from autopilot clear times.
 * par = ceil(autopilot clear time * 1.25) — a brisk-but-human target.
 * Run after adding/removing a level file. Lanes never edit pars.js. */
import { createRequire } from 'node:module';
import { readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const DIR = dirname(fileURLToPath(import.meta.url));
require(join(DIR, 'engine.js'));
require(join(DIR, 'autopilot.js'));
const A = globalThis.HardestAutopilot;

const files = readdirSync(join(DIR, 'levels')).filter(f => f.endsWith('.js')).sort();
const pars = {};
for (const f of files) {
  globalThis.HARDEST_LEVELS = [];
  require(join(DIR, 'levels', f));
  const lvl = globalThis.HARDEST_LEVELS[0];
  if (!lvl || !Number.isInteger(lvl.id)) { console.error(`skip ${f}: no level`); continue; }
  const r = A.solve(lvl, { maxSim: 120, maxDeaths: 400 });
  if (!r.clear) { console.error(`skip ${f}: autopilot FAIL (${r.reason})`); continue; }
  pars[lvl.id] = Math.ceil(r.time * 1.25);
}
const body = `/* GENERATED by gen-pars.mjs — do not edit by hand. */
globalThis.HARDEST_PARS = ${JSON.stringify(pars)};
`;
writeFileSync(join(DIR, 'pars.js'), body);
console.log(`pars.js: ${Object.keys(pars).length} pars`);
