/* Level 23 — Tempo. Teaches: mixed-speed patrols make familiar lanes' safe windows shift. */
(globalThis.HARDEST_LEVELS = globalThis.HARDEST_LEVELS || []).push({
  id: 23,
  name: 'Tempo',
  map: [
    '##########################',
    '#SS......................#',
    '#........................#',
    '#....C...................#',
    '#........................#',
    '#..............C.........#',
    '#........................#',
    '#...........K............#',
    '#........................#',
    '#..................C.....#',
    '#........................#',
    '#......................C.#',
    '#........................#',
    '#......................GG#',
    '##########################',
  ],
  patrols: [
    { path: [[3, 2], [21, 2]], speed: 80, mode: 'pingpong', phase: 0 },
    { path: [[21, 2], [3, 2]], speed: 180, mode: 'pingpong', phase: 0.5 },
    { path: [[5, 4], [22, 4]], speed: 110, mode: 'pingpong', phase: 0.2 },
    { path: [[22, 4], [5, 4]], speed: 220, mode: 'pingpong', phase: 0.7 },
    { path: [[3, 6], [20, 6]], speed: 90, mode: 'pingpong', phase: 0.4 },
    { path: [[20, 6], [3, 6]], speed: 160, mode: 'pingpong', phase: 0.9 },
    { path: [[5, 8], [22, 8]], speed: 120, mode: 'pingpong', phase: 0.1 },
    { path: [[22, 8], [5, 8]], speed: 200, mode: 'pingpong', phase: 0.6 },
    { path: [[3, 10], [21, 10]], speed: 100, mode: 'pingpong', phase: 0.3 },
    { path: [[21, 10], [3, 10]], speed: 210, mode: 'pingpong', phase: 0.8 },
  ],
});
