/* Level 80 — Eighty. Second final exam: long key route, door barrier, and paired teleports. */
(globalThis.HARDEST_LEVELS = globalThis.HARDEST_LEVELS || []).push({
  id: 80,
  name: 'Eighty',
  map: [
    '##############################',
    '#SS...........#..............#',
    '#SS..T..C.....#.....C........#',
    '#....y........#..............#',
    '#.......C.....#..T...........#',
    '#..y..........D..............#',
    '#.............#..............#',
    '#......C......#.......C......#',
    '#.............#..............#',
    '#..y..........D....C.........#',
    '#.............#..............#',
    '#.............#..............#',
    '#.......C.....D..............#',
    '#.............#.......K......#',
    '#.............#..............#',
    '#....T........#...T.........G#',
    '#.............#..............#',
    '##############################',
  ],
  patrols: [
    { path: [[2, 3], [12, 3]], speed: 150, mode: 'pingpong' },
    { path: [[2, 7], [12, 7]], speed: 165, mode: 'pingpong', phase: 0.5 },
    { path: [[2, 11], [12, 11]], speed: 180, mode: 'pingpong' },
    { path: [[3, 14], [12, 14]], speed: 195, mode: 'pingpong', phase: 0.5 },
    { path: [[3, 16], [12, 16]], speed: 210, mode: 'pingpong' },
    { path: [[16, 2], [27, 2]], speed: 150, mode: 'pingpong', phase: 0.5 },
    { path: [[16, 4], [27, 4]], speed: 165, mode: 'pingpong' },
    { path: [[16, 6], [27, 6]], speed: 180, mode: 'pingpong', phase: 0.5 },
    { path: [[16, 8], [27, 8]], speed: 195, mode: 'pingpong' },
    { path: [[16, 10], [27, 10]], speed: 210, mode: 'pingpong', phase: 0.5 },
    { path: [[16, 12], [27, 12]], speed: 220, mode: 'pingpong' },
    { path: [[18, 3], [18, 15]], speed: 230, mode: 'pingpong', phase: 0.5 },
    { path: [[22, 3], [22, 15]], speed: 240, mode: 'pingpong' },
    { path: [[26, 3], [26, 15]], speed: 250, mode: 'pingpong', phase: 0.5 },
  ],
});
