/* Level 73 — Keyhole. Two keys unlock narrow one-tile corridors; commit through timed gaps. */
(globalThis.HARDEST_LEVELS = globalThis.HARDEST_LEVELS || []).push({
  id: 73,
  name: 'Keyhole',
  tier: 'INHUMAN',
  map: [
    '############################',
    '#SS....#......#............#',
    '#SS....#......#............#',
    '#..C.y.#......D....C.......#',
    '#......#......#............#',
    '#......########............#',
    '#......#......#............#',
    '#..C...#......#......C.....#',
    '#......#......#............#',
    '#......########............#',
    '#....y.#......D............#',
    '#......#......#............#',
    '#......#......#............#',
    '#......#......#............#',
    '#......#......#............#',
    '#.........................G#',
    '############################',
  ],
  patrols: [
    { path: [[2, 3], [6, 3]], speed: 140, mode: 'pingpong' },
    { path: [[2, 7], [6, 7]], speed: 155, mode: 'pingpong', phase: 0.5 },
    { path: [[2, 12], [6, 12]], speed: 145, mode: 'pingpong' },
    { path: [[9, 2], [12, 2]], speed: 160, mode: 'pingpong', phase: 0.5 },
    { path: [[16, 8], [23, 8]], speed: 175, mode: 'pingpong' },
    { path: [[9, 13], [12, 13]], speed: 150, mode: 'pingpong', phase: 0.5 },
    { path: [[16, 2], [24, 2]], speed: 180, mode: 'pingpong' },
    { path: [[18, 7], [25, 7]], speed: 200, mode: 'pingpong', phase: 0.5 },
    { path: [[16, 12], [24, 12]], speed: 190, mode: 'pingpong' },
    { path: [[16, 4], [16, 14]], speed: 210, mode: 'pingpong', phase: 0.25 },
    { path: [[21, 3], [21, 14]], speed: 220, mode: 'pingpong', phase: 0.75 },
  ],
});
